# Generated by Django 4.2.2 on 2023-06-19 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('media', models.ImageField(upload_to='./project_media/')),
                ('deadline', models.DateTimeField()),
                ('price_min', models.DecimalField(decimal_places=1, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=1, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Required_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='projects.projects')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skills')),
            ],
        ),
    ]
