# Generated by Django 4.2.2 on 2023-06-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='required_skill',
            name='project',
        ),
        migrations.RemoveField(
            model_name='required_skill',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Required_Skill',
        ),
    ]
