# Generated by Django 4.2.2 on 2023-06-21 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_initial'),
        ('projects', '0004_remove_required_skill_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4096)),
                ('media', models.URLField(max_length=256)),
                ('deadline', models.DateTimeField()),
                ('price_min', models.DecimalField(decimal_places=1, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=1, max_digits=10)),
                ('status', models.CharField(choices=[('hiring', 'Hiring'), ('communication', 'Communication'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('conflict', 'Conflict')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Required_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='projects.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skill')),
            ],
        ),
    ]
