# Generated by Django 4.2.2 on 2023-06-24 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_available_skills_freelancers_messages_skills_users_and_more'),
        ('projects', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='required_skill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skills'),
        ),
    ]
