# Generated by Django 4.2.2 on 2023-06-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_required_skill_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price_max',
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_min',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('hiring', 'Hiring'), ('communication', 'Communication'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('conflict', 'Conflict')], default='hiring', max_length=20),
        ),
    ]
