# Generated by Django 4.2.2 on 2023-06-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employments',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='employments',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.DeleteModel(
            name='Employments',
        ),
    ]
