# Generated by Django 4.2.2 on 2023-06-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employments',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='employments',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Employments',
        ),
    ]
