# Generated by Django 4.2.2 on 2023-07-06 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_offer_id_alter_offer_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
