# Generated by Django 4.2.2 on 2023-07-06 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0008_rename_employment_employment_application_and_more'),
        ('offers', '0003_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_time', models.DateTimeField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='applications.application')),
            ],
        ),
    ]
