# Generated by Django 4.2.2 on 2023-07-06 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_rename_employment_employment_application_and_more'),
        ('offers', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='id',
        ),
        migrations.AlterField(
            model_name='offer',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='application', serialize=False, to='applications.application'),
        ),
    ]
