# Generated by Django 4.2.2 on 2023-06-19 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('firstname', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('is_moderator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('msg_date', models.DateTimeField()),
                ('msg_content', models.CharField(max_length=256)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='users.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Freelancers',
            fields=[
                ('freelancer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
