# Generated by Django 4.2.2 on 2023-06-19 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Freelancers',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
