# Generated by Django 4.2.2 on 2023-06-19 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_messages_receiver_remove_messages_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('firstname', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('is_moderator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('msg_date', models.DateTimeField()),
                ('msg_content', models.CharField(max_length=256)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='users.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Freelancers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancing', to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Available_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_skills', to='users.users')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skills')),
            ],
        ),
    ]
