# Generated by Django 4.2.2 on 2023-06-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_required_skills_project_and_more'),
        ('applications', '0002_remove_employments_employment_and_more'),
        ('transactions', '0002_delete_payments'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancers',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Available_Skills',
        ),
        migrations.DeleteModel(
            name='Freelancers',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
