# Generated by Django 4.2.2 on 2023-06-24 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_available_skills_freelancers_messages_skills_users_and_more'),
        ('projects', '0006_alter_required_skill_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='users.users'),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='users.users'),
        ),
        migrations.AddField(
            model_name='freelancers',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancing', to='users.users'),
        ),
        migrations.AddField(
            model_name='available_skills',
            name='freelancer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='available_skills', to='users.users'),
        ),
        migrations.AddField(
            model_name='available_skills',
            name='skill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.skills'),
        ),
    ]
