# Generated by Django 4.2.2 on 2023-06-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_skill_messages_receiver_messages_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancers',
            name='rating',
            field=models.FloatField(default=1),
        ),
    ]
